"""One-off migration: backfill Period.promoted_from on period records that
were generated by a save_timeline_role() promotion before that field
existed, matched by the "<polity_id>_period" filename convention against a
polity whose own timeline_role is "period" or "both". See
docs/plans/2026-09-05-polity-period-conversion-friction-design.md."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent


def _load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main(root: Path = ROOT, *, dry_run: bool = False) -> dict[str, int]:
    summary = {"backfilled": 0}
    promoted_polity_ids = {
        path.stem
        for path in sorted((root / "polities").glob("*.yaml"))
        if _load_yaml(path).get("timeline_role") in {"period", "both"}
    }
    for path in sorted((root / "periods").glob("*.yaml")):
        if not path.stem.endswith("_period"):
            continue
        source_polity_id = path.stem[: -len("_period")]
        if source_polity_id not in promoted_polity_ids:
            continue
        document = _load_yaml(path)
        if document.get("promoted_from"):
            continue
        document["promoted_from"] = source_polity_id
        summary["backfilled"] += 1
        if not dry_run:
            path.write_text(
                yaml.safe_dump(document, sort_keys=False, allow_unicode=True), encoding="utf-8"
            )
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    result = main(dry_run=args.dry_run)
    print(f"Backfilled {result['backfilled']} period record(s)" + (" (dry run)" if args.dry_run else ""))
