"""One-shot authoring script for the hand-curated regional-era starter set
(macro chapters 1-5 only -- Task 4 Part A of the period-ontology plan). Run
once; re-running is safe (overwrites its own files with the same content).
Not part of the recurring pipeline sequence.

# TODO: a few of the auto-built source_urls below (built from canonical_name)
# won't resolve to a real Wikipedia article -- known rough edge, not blocking
# (schema only checks the URL is a string). Fix opportunistically."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PERIODS_DIR = ROOT / "periods"

# (id, canonical_name, macro_chapter_id, start, end, continents, notes)
REGIONAL_ERAS: list[dict] = [
    # african_paleolithic_era and eurasian_paleolithic_era originated here but
    # were demoted to tier=period (reparented under the new overarching
    # paleolithic_era) on 2026-08-30 -- see ONTOLOGY.md's "Overarching regional
    # eras for genuinely cross-regional themes". Removed from this table for
    # the same reason as the Neolithic/Bronze Age rows below.
    # fertile_crescent_neolithic_era, nile_valley_neolithic_era, and
    # east_asian_neolithic_era originated here but were demoted to tier=period
    # (reparented under the new overarching neolithic_era) on 2026-08-30 -- see
    # ONTOLOGY.md's "Overarching regional eras for genuinely cross-regional
    # themes". Removed from this table so a re-run of this script can't
    # silently revert that restructuring; their periods/*.yaml files are
    # maintained by hand from here on, not regenerated by this script.
    # mesoamerican_archaic_era and andean_archaic_era originated here but were
    # demoted to tier=period (reparented under the now-renamed "Neolithic &
    # Archaic" neolithic_era) on 2026-08-31 -- see ONTOLOGY.md's "Overarching
    # regional eras for genuinely cross-regional themes". Removed from this
    # table for the same reason as the Paleolithic/Neolithic/Bronze Age rows.
    dict(
        id="mesopotamian_early_states_era",
        canonical_name="Mesopotamian Early States",
        broader_periods=["macro_early_cities_states"],
        start=-3500,
        end=-1200,
        continents=["asia"],
        notes="Uruk period through the Bronze Age Collapse.",
    ),
    # egyptian_early_states_era originated here but was deleted outright (not
    # demoted, unlike the other removed rows below) on 2026-08-31: it was
    # redundant with ancient_egypt_period, the existing "civilization-as-
    # backdrop" period already carrying Ancient Egypt's Civilizations &
    # Cultures lane presence, and nothing else nested under it (no other
    # period pointed broader_periods at it, and no Egypt-specific period
    # records existed to heuristically match its geography/dates either).
    # east_asian_bronze_age_era and european_bronze_age_era originated here
    # but were demoted to tier=period (reparented under the new overarching
    # bronze_age_era) on 2026-08-30 -- see ONTOLOGY.md's "Overarching regional
    # eras for genuinely cross-regional themes". Removed from this table for
    # the same reason as the Neolithic trio above.
    # mediterranean_classical_era, east_asian_classical_era,
    # south_asian_classical_era, mesoamerican_formative_classic_era, and
    # andean_early_civilizations_era originated here but were demoted to
    # tier=period (reparented under the new overarching classical_antiquity_era)
    # on 2026-08-31 -- same "overarching regional era" treatment as the
    # Neolithic/Bronze Age/Paleolithic/Iron Age rows. Removed from this table
    # for the same reason as those.
    # sub_saharan_african_iron_age_era originated here but was demoted to
    # tier=period (reparented under the new overarching iron_age_era) on
    # 2026-08-31 -- same "overarching regional era" treatment as the
    # Neolithic/Bronze Age/Paleolithic rows above. Removed from this table for
    # the same reason as those.
    dict(
        id="medieval_europe_era",
        canonical_name="Medieval Europe",
        broader_periods=["macro_postclassical_worlds"],
        start=500,
        end=1500,
        continents=["europe"],
        notes="Early, High, and Late Middle Ages, including the Byzantine "
        "Empire.",
    ),
    dict(
        id="islamic_caliphates_era",
        canonical_name="Islamic Caliphates and Sultanates",
        broader_periods=["macro_postclassical_worlds"],
        start=622,
        end=1500,
        continents=["asia", "africa"],
        notes="Rashidun Caliphate through the rise of the Ottoman, Safavid, "
        "and Mughal gunpowder empires.",
    ),
    dict(
        id="east_asian_imperial_era",
        canonical_name="East Asian Imperial Dynasties (Post-Classical)",
        broader_periods=["macro_postclassical_worlds"],
        start=500,
        end=1500,
        continents=["asia"],
        notes="Tang through Ming China; Heian through Muromachi Japan; "
        "Goryeo Korea.",
    ),
]


def build_period(row: dict) -> dict:
    return {
        "id": row["id"],
        "canonical_name": row["canonical_name"],
        "kind": "historical",
        "tier": "regional_era",
        "start": row["start"],
        "end": row["end"],
        "start_confidence": "low",
        "end_confidence": "low",
        "geography": {"continents": row["continents"]},
        "broader_periods": row["broader_periods"],
        "successors": [],
        "authority": "Histomap editorial: regional-era starter set",
        "external_ids": {},
        "notes": row["notes"],
        "source_urls": ["https://en.wikipedia.org/wiki/" + row["canonical_name"].replace(" ", "_")],
    }


def main() -> None:
    for row in REGIONAL_ERAS:
        document = build_period(row)
        path = PERIODS_DIR / f"{row['id']}.yaml"
        path.write_text(
            yaml.safe_dump(document, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    print(f"wrote {len(REGIONAL_ERAS)} regional-era period files")


if __name__ == "__main__":
    main()
